### PR TITLE
refactor(luasnip): use ctx.cursor instead of vim.api.nvim_win_get_cursor(0)

### PR DESCRIPTION
**Pull request by stefanboca**
Just a small improvement I noticed

### CODE REVIEW

**Comment by Saghen** [comment]
Thanks!

**Comment by soifou** [comment]
This change cause the following error for one-liner snippets:

```
failed to execute item with error: .../.local/share/nvim/lazy/LuaSnip/lua/luasnip/init.lua:272: 'start' is higher than 'end'
```

**Comment by Saghen** [comment]
Ah because the completion being accepted causes the cursor position to move, so the context is out of date. Fixed on `main`

**Comment by stefanboca** [comment]
My bad, should have tested more. Sorry for the trouble

**Pull request merged**
