### PR TITLE
perf: fix redundant docs rendering

### PR DESCRIPTION
**Pull request by eero-lehtinen**
After 05229ddc2fd1695c979e2807aa96842978dd4779 adding the use of `stylize_markdown`, I consistently experience half second stutters when docs are open and switching between items. Nvim-cmp has zero issues with this.

Basically I copied what nvim-cmp does, which removed all performance issues for me.  The buffer is cleared more efficiently. `nvim_buf_set_lines` is not used redundantly only to be instantly overridden by `stylize_markdown`. Setting the "modified" option is moved to the end of the function.

### CODE REVIEW

**Review by scottmckendry — APPROVED** [review]

**Comment by scottmckendry** [comment]
I've A-B tested doc performance with both this PR and main and there definitely an improvement here, however slight. 

I did notice the doc output looks different. For example, this is main:
image

And with your changes:
image

The latter looks better, IMO. Any idea why this is?

**Comment by eero-lehtinen** [comment]
I'm not sure why `main` looks different to you. For me this PR looks the same.

Also the lag seems to be much more pronounced with rust-analyzer for some reason. With lua_ls it didn't really make a difference.

The lag is also much worse on nightly.

`main` with nvim nightly (After the first 6 secs I start tapping quickly and it stutters badly):

[Screencast_20241015_123926.webm](https://github.com/user-attachments/assets/08690613-5711-4716-8f9b-860dfea04d8f)

this PR with nvim nightly (I'm tapping just as quick and there is no stutter):

[Screencast_20241015_124018.webm](https://github.com/user-attachments/assets/006f3767-49c2-44bd-84ca-8650af740eb8)

It doesn't show that well on video because KDE Spectacle seems to add its own lag but it feels way better.

**Comment by Saghen** [comment]
Thanks for finding this regression! I wasn't happy with the performance even if we cached it and noticed that it was using regex highlighting instead of treesitter. I took inspiration from the vim.treesitter.highlighter code to highlight the documentation window ourselves. It has a high initial cost of 50ms for compiling the `markdown` query, but afterwards, it updates in a few ms. Lmk if performance looks good on your end

**Comment by eero-lehtinen** [comment]
Performance feels great now. Also looks better with treesitter. Thanks!

**Pull request closed without merging**
