### PR TITLE
feat: align completion window

### LINKED ISSUE #221: Align completions to buffer text in reversed draw mode
nvim-cmp aligns completions underneath the buffer text:

Screenshot 2024-10-30 at 23 52 28

<p>

blink.cmp, when in `reversed` draw mode has them offset by a character:

Screenshot 2024-10-30 at 23 53 12

<p>

Having them aligned to the buffer text both looks better and makes the completion menu visually easier to use.

### PR DESCRIPTION
**Pull request by lopi-py**
closes #221

image

### CODE REVIEW

**Comment by Saghen** [comment]
Ideally we would position the window based on the position of the label so it works for any draw function. I'm not sure that's possible without a larger rework though. Lmk if you have thoughts, I'll likely accept this in the interim

**Comment by lopi-py** [comment]
Currently we don't have any way to detect the label position so yeah that will need a refactor for the rendering, I think it could be related to https://github.com/Saghen/blink.cmp/issues/154. We can have this in the meantime

**Comment by Saghen** [comment]
Thanks!

**Comment by net** [comment]
> Ideally we would position the window based on the position of the label so it works for any draw function.

At that point it should probably be a setting, as I think I would only want to align the label when it's the first element in the row.

**Pull request merged**
