### PR TITLE
feat: add labelDetails support

### PR DESCRIPTION
**Pull request by 0xJWLabs**

### CODE REVIEW

**Review by 0xJWLabs — COMMENTED** [review]
Well we can also do with ctx.item.labelDetails btw, I just realised this.

**Comment by Saghen** [comment]
Yep that's preferred

**Comment by KingMichaelPark** [comment]
@Saghen excuse my ignorance but I spent a while looking for how to add the import source using the transform_items function on the lsp but couldn't get it to work. Could you show me an example of how that would be done?

I am guessing we need to do something here:
```lua
    sources = {
        providers = {
            lsp = {
                transform_items = function(ctx, items)
                    vim.print(vim.inspect(ctx))
                    vim.print("***")
                    vim.print(vim.inspect(items))

                    return items
                end,
            }
        }
    }
```
in the config but I can't seem to get it to work.
This option shows the import 
```lua
        windows = {
            documentation = {
                auto_show = true
            },
```
but there is a noticeable lag while it loads so it I can load it faster then that would be preferred. If that is simply down to the lsp though, then that's fine. Cheers!

**Comment by Saghen** [comment]
There's `auto_show_delay` that you could make `0` to immediately load it but otherwise, it's up to the LSP

**Pull request closed without merging**
