### PR TITLE
implement new behavior for autocompletion menu, toggle option to require keypress for showing suggestions.

### PR DESCRIPTION
**Pull request by Jezda1337**
This introduces a new `auto_show` config for the autocompletion menu. It's set to `true` by default, so nothing has changed. If we set it to `false,` then we need to press default or user-set keymaps to show the menu.

### CODE REVIEW

**Comment by neochrome** [comment]
This sounds like an awesome addition, which I think would solve #52

**Comment by Jezda1337** [comment]
Based on the #52 code example, the plugin will be partially disabled for the specific file type that the user configures; the PR is more general, it is meant to disable the whole autocompletion window and trigger it on default or user configure keybindings

**Comment by neochrome** [comment]
For my use-case I think this PR would be even better. I don't really want to have the behavior different on a per file type basis, rather turn of autocompletion at all since I hate things that pop up automagically while I'm typing. I want to control the behavior using a keymap at all times :) But that's me :)

**Comment by Saghen** [comment]
Thank you!

**Comment by Jezda1337** [comment]
Sorry for the messy code :)

**Pull request merged**
