### PR TITLE
feat(cmdline): allow configuring separate cmdline preset

### LINKED ISSUE #514: Add separate keymap settings for `cmdline` completions.
### Feature Description

Since the addition of `cmdline` completions, it would be really nice to have separate keymap settings for `cmdline` completions as they may clash with keymaps for normal completions.

### PR DESCRIPTION
**Pull request by folke**
This PR does two things:
- allow configuring a different keymap for the `cmdline`
- added a default preset more closely matching the default Neovim cmdline keymaps

Closes #514

### CODE REVIEW

**Comment by folke** [comment]
Thinking about this more, specifically for the cmdline, users will probably want to customize other config options as well.
Like `auto_insert` etc, so maybe a better approach (but way more code changes) would be to allow a complete different config for the cmdline.

**Comment by folke** [comment]
This PR is indeed not enough.
Personally I'd want to have `auto_insert` enabled, but with no `preselect` and use `<tab>` / `<S-Tab>` to cycle between results.

Not sure what the best approach is.

**Comment by Saghen** [comment]
> so maybe a better approach (but way more code changes) would be to allow a complete different config for the cmdline.

That would make the entire config dynamic which would make this much more complicated. I'd like to avoid this if possible

> Personally I'd want to have `auto_insert` enabled, but with no `preselect` and use `<tab>` / `<S-Tab>` to cycle between results.

So you'd like `auto_insert` in default mode and `preselect` in cmdline mode just to clarify?

**Comment by folke** [comment]
I think so? :)
I don't have anything configured regarding preselect and auto_insert right now for blink.

I want to achieve a similar setup as with the regular cmdline, as in:

When I type `T`, the menu opens like this:
image

`<tab>` then cycles forward (`<s-tab>` backwards) and inserts the items when doing so, so you can press `<cr>` anytime to exeucte

image
image

**Comment by folke** [comment]
These are the options I set:

```lua
vim.opt.completeopt = "menu,menuone,noselect"
```

**Comment by folke** [comment]
The screenshots are Noice obviously, but that behaves exactly as the normal cmdline regarding completion.

**Comment by the-fuckin-nobody** [comment]
> So you'd like auto_insert in default mode and preselect in cmdline mode just to clarify?

Maybe make `blink.cmp.select_next()` take an extra argument of type same as `blink.cmp.config.completion.list.selection` ?

So we can set keymaps like this:
```
['<Tab>'] = {
function(cmp)
    if vim.fn.getcmdtype() == '' then
        return cmp.select_next({select_behaviour = 'preselect'})
    end
    return cmp.select() -- selection_behaviour defaults to `auto_insert`
end }
```

**Comment by folke** [comment]
@the-fuckin-nobody though about doing it that way initially, but in my case, the first entry would already be pre-selected, so you can't use `<tab>` to next&insert then.

**Comment by the-fuckin-nobody** [comment]
> @the-fuckin-nobody though about doing it that way initially, but in my case, the first entry would already be pre-selected, so you can't use `<tab>` to next&insert then.

If I am understanding it correctly, is this the desired behaviour?


https://github.com/user-attachments/assets/51bbf44e-e2e3-4819-9bfe-af9622999d49

**Comment by folke** [comment]
Yep, exactly.

**Comment by the-fuckin-nobody** [comment]
> Yep, exactly.

Then, it is actually doable with the current state of the plugin, by configuring the tab  keymap like this like this:

```lua
["<Tab>"] = {
				function(cmp)
					if vim.fn.getcmdtype() ~= "" then
						return cmp.select_next()
					elseif cmp.snippet_active() then
						return cmp.accept()
					end
				end,
				"snippet_forward",
				"fallback",
			},
```

But in my case I would prefer to have selection behaviour as `preselct` for normal completion menu and `auto_insert` for cmdline completion menu.

**Comment by folke** [comment]
> But in my case I would prefer to have selection behaviour as preselct for normal completion menu and auto_insert for cmdline completion menu.

Yep same here

**Comment by the-fuckin-nobody** [comment]
> Yep same here

image
I just found this line while skimming through the codebase , but `skip_auto_insert` has not been implemented yet. Implementing this may achieve the purpose

**Comment by Parsifa1** [comment]
any progress about handling the 'special' auto_insert for cmdline?

**Comment by the-fuckin-nobody** [comment]
> any progress about handling the 'special' auto_insert for cmdline?

That should be done in another PR I guess cuz its unrelated to this PR(`cmdline keymaps`).

**Comment by Saghen** [comment]
Yep, I'm still working out how I want to solve it

**Comment by the-fuckin-nobody** [comment]
> Yep, I'm still working out how I want to solve it

Take a break bro not everything must be implemented right away!

PS: You're awesome

**Comment by Parsifa1** [comment]
> any progress about handling the 'special' auto_insert for cmdline?

for those who find here and want some temp fix:
here is a snippet💖:
(remember to set `<CR>` to `{}` )
```lua
init = function()
        -- FIX: Temporary for not being able to set auto_insert for cmdline
        local orig_list_selection = nil
        vim.api.nvim_create_autocmd("CmdlineEnter", {
            callback = function()
                local list = require "blink.cmp.completion.list"
                orig_list_selection = list.config.selection
                list.config.selection = "auto_insert"
            end,
        })
        vim.api.nvim_create_autocmd("CmdlineLeave", {
            callback = function()
                if orig_list_selection then
                    local list = require "blink.cmp.completion.list"
                    list.config.selection = orig_list_selection
                end
            end,
        })
    end,
```

ref https://github.com/Parsifa1/nvim/blob/4ce2ab13d428f3efa6ae269bff030f033f59dceb/lua/plugins/lsp/blink.lua

**Pull request merged**
