### PR TITLE
fix(accept): schecule `fuzzy.access` using uv.new_work

### PR DESCRIPTION
**Pull request by stefanboca**

### CODE REVIEW

**Comment by Saghen** [comment]
I think ideally the uv.new_work would be inside the access function so consumers don't have to worry about it

**Comment by stefanboca** [comment]
Good idea, I'll make the change.

This is actually not working currently, because tables (`item`) can't be passed as thread args. I didn't realize this at first because everything was running in a context where errors were silent.

**Comment by Saghen** [comment]
You might want to use the built in message pack API to serialize it before sending

**Comment by stefanboca** [comment]
Just did a quick benchmark: for a roundtrip encode/decode on a typical item, `vim.mpack` takes ~0.02ms, while `string.buffer` takes ~0.002ms. The cost is so small that IMO it's not worth dynamically detecting if string.buffer is available.

**Comment by Saghen** [comment]
Looks great, thank you!

**Pull request merged**
