### PR TITLE
fix: make ghost-text extmark with pcall

### LINKED ISSUE #257: ghost text: invalid 'col' out of range
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

this only happens on large rust project, where rust analyzer is slow to give response. there is a lot of "rust-analyzer: -32802: server cancelled the request". there is completion after like 500ms when rust analyzer give the response.
the problem might not be much the late response, but maybe also rust analyzer returning big function / types which are sometimes bigger than the screen 
```
  Error  10:32:04 notify.error rust-analyzer: -32802: server cancelled the request
   Error  10:32:05 msg_show.lua_error Error executing vim.schedule lua callback: ...nvim/lazy/blink.cmp/lua/blink/cmp/windows/ghost-text.lua:61: Invalid 'col': out of range
stack traceback:
	[C]: in function 'nvim_buf_set_extmark'
	...nvim/lazy/blink.cmp/lua/blink/cmp/windows/ghost-text.lua:61: in function 'show_preview'
	...nvim/lazy/blink.cmp/lua/blink/cmp/windows/ghost-text.lua:15: in function 'callback'
	...im/lazy/blink.cmp/lua/blink/cmp/windows/autocomplete.lua:313: in function 'emit_on_select'
	...im/lazy/blink.cmp/lua/blink/cmp/windows/autocomplete.lua:157: in function 'open_with_items'
	.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:57: in function <.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:51>
```

### Relevant configuration

```lua
windows = {
        ghost_text = {
          enabled = true,
        },
      },
```

### neovim version

NVIM v0.10.2 Build type: RelWithDebInfo LuaJIT 2.1.1727870382

### `blink.cmp` version: branch, tag, or commit

d3e1c92

### PR DESCRIPTION
**Pull request by eero-lehtinen**
Fixes #257 

This issue also happens to me in a large Rust project where the LSP is slow. It tries to show a slightly outdated text edit and errors, but shows the correct text edit instantly after. So maybe this could also be fixed with better scheduling.

Now I just make the extmark with pcall to not render outdated ghost-texts and cause errors. Nvim-cmp also does this.

### CODE REVIEW

**Comment by idelice** [comment]
This introduces another error that I've experienced by using your changes:

```
   Error  10:14:28 msg_show.lua_error Error executing vim.schedule lua callback: ...e/projects/blink.cmp/lua/blink/cmp/accept/text-edits.lua:89: index out of range
stack traceback:
	[C]: in function 'get_line_byte_from_position'
	...e/projects/blink.cmp/lua/blink/cmp/accept/text-edits.lua:89: in function 'get_from_item'
	.../projects/blink.cmp/lua/blink/cmp/windows/ghost-text.lua:68: in function 'draw_preview'
	.../projects/blink.cmp/lua/blink/cmp/windows/ghost-text.lua:53: in function 'show_preview'
	.../projects/blink.cmp/lua/blink/cmp/windows/ghost-text.lua:34: in function 'callback'
	...rojects/blink.cmp/lua/blink/cmp/windows/autocomplete.lua:283: in function 'emit_on_select'
	...rojects/blink.cmp/lua/blink/cmp/windows/autocomplete.lua:129: in function 'open_with_items'
	.../ibrahimdelice/projects/blink.cmp/lua/blink/cmp/init.lua:57: in function <.../ibrahimdelice/projects/blink.cmp/lua/blink/cmp/init.lua:51>
```

**Comment by eero-lehtinen** [comment]
Ok. I have zero issues at least with rust-analyzer, but another solution is probably necessary.

**Comment by Saghen** [comment]
Thanks! I believe I found the root cause to be from the offset applied to text edits

**Comment by eero-lehtinen** [comment]
Seems to work :+1:

**Pull request merged**
