### PR TITLE
Add basic event trigger API

### PR DESCRIPTION
**Pull request by dsully**
This allows for `copilot.lua` (and others I'm sure) ghost text to be hidden when the completion menu is shown:

```lua
            -- Remove Copilot ghost text when the cmp menu is opened.
            ev.on_load("blink.cmp", function()
                vim.schedule(function()
                    local cmp = require("blink.cmp")

                    cmp.on_show(function()
                        require("copilot.suggestion").dismiss()
                        vim.api.nvim_buf_set_var(0, "copilot_suggestion_hidden", true)
                    end)

                    cmp.on_hide(function()
                        vim.api.nvim_buf_set_var(0, "copilot_suggestion_hidden", false)
                    end)
                end)
            end)
```

I'm not sure of the best place to document this at the moment.

Fix some typos and syntax issue in the README as well.

### CODE REVIEW

**Comment by Saghen** [comment]
I believe you're looking to track the `cmp.autocomplete` window's visibility instead of the trigger. Also please drop the changes to the formatting on the default configuration. Thanks for the grammar fixes on the rest of the README :smile:

**Comment by dsully** [comment]
You're right - let me update.

**Comment by dsully** [comment]
Done. 

I added additional type hints, and I also left my changes to the trigger.event_triggers. 

Let me know if you'd like those reverted.

**Comment by Saghen** [comment]
Yeah, would be great if you could revert the changes to signature help and trigger. I'll end up extracting the event targets into their own module for #82

**Comment by Saghen** [comment]
Thank you!

**Comment by dsully** [comment]
Oh - looks like you merged already. Do you want the signature help and trigger reverting in another PR?

**Pull request merged**
